CREATE TABLE IF NOT EXISTS feedback (
 id TEXT PRIMARY KEY NOT NULL,
 user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 message TEXT NOT NULL,
 context TEXT NOT NULL,
 created_at INTEGER NOT NULL
);
