import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {parseHTML} from 'linkedom';
import {experimentLink} from '../public/experiment-links.js';
import {initialParameters,duration,sample} from '../public/physics.js';
const a=sample('projectile',{v:10,h:19.6},2),b=sample('projectile',{v:20,h:19.6},2);
assert.equal(duration('projectile',{v:10,h:19.6}),2);assert.equal(a.y,b.y);assert.equal(a.y,0);assert.equal(a.x,20);assert.equal(b.x,40);
const link=experimentLink('projectile',{v:20,h:19.6},'https://physics.example/');assert.equal(link.searchParams.get('v0'),'20');assert.equal(link.searchParams.get('h'),'19.6');assert.equal(link.searchParams.get('g'),'9.8');
assert.equal(experimentLink('projectile',{v0:20,h:19.6,angle:30},'https://physics.example/'),null);
assert.equal(experimentLink('projectile',{v0:200,h:19.6},'https://physics.example/'),null);
assert.equal(experimentLink('lens',{},'https://physics.example/').searchParams.get('experiment'),'lens');
assert.equal(experimentLink('relativity',{},'https://physics.example/'),null);
const {document}=parseHTML(await readFile('public/index.html','utf8'));
for(const id of ['compare-scene','compare-play','compare-reset','compare-slider','retry-question','forgot-password','send-verification','share-site'])assert(document.getElementById(id));
assert.equal(document.documentElement.dataset.theme,'dark');
const image=await readFile('public/cover.jpg');assert.deepEqual([...image.subarray(0,3)],[255,216,255]);
const projectile=await readFile('public/physics-lab/experiments/projectile.html','utf8');assert(projectile.includes('= −<i class="v">g</i>'));assert(projectile.includes('el.value=P[key]'));
assert.equal(initialParameters.projectile.h,19.6);
console.log('Cinematic page anchors, dual-ball physical calculation, safe 2D/3D transfer, coordinate sign, binary image and default theme PASS.');
